#!/usr/bin/env ruby

require './lib/dagon/tokenizer'

def read_program
  if ARGV[0]
    File.read(ARGV[0])
  else
    STDIN.read
  end
end

tokenizer = Dagon::Tokenizer.new
tokens = tokenizer.tokenize read_program
puts tokens.inspect

