#!/usr/bin/env ruby

require './lib/dagon/tokenizer'
require './lib/dagon/interpreter'
require './lib/dagon/ast/generator'

def read_program
  if ARGV[0]
    File.read(ARGV[0])
  else
    STDIN.read
  end
end

tokenizer = Dagon::Tokenizer.new
tokens = tokenizer.tokenize read_program

ast = Ast::Generator.new(tokens).parse.table

puts ast.inspect
interpreter = Dagon::Interpreter.new(ast)
interpreter.run
