#!/usr/bin/env ruby

require './lib/dagon/tokenizer'
require './lib/dagon/interpreter'

def read_program
  if ARGV[0]
    File.read(ARGV[0])
  else
    STDIN.read
  end
end

tokenizer = Dagon::Tokenizer.new
tokens = tokenizer.tokenize read_program

# ast = Ast::Generator.new.parse.table
ast = [:program, [:call, [:identifier, 'puts'], [:integer, 5]]]

interpreter = Dagon::Interpreter.new(ast)
interpreter.run
