#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'


module Ast
  class Generator < Racc::Parser

module_eval(<<'...end generator.y/module_eval...', 'generator.y', 35)
  attr_accessor :table
  def initialize(tokens)
    @tokens = tokens
  end

  def parse
    @table = do_parse
    self
  end

  def next_token
    tokens.shift
  end

  private
  attr_accessor :tokens
...end generator.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    27,    28,    29,    30,    31,    15,   -13,    25,   -14,    10,
    11,    12,    32,    18,    18,    10,    11,    12,    15,    14,
    16,    10,    11,    12,    10,    11,    12,    10,    11,    12,
    15,    19,   -16,    18,    36,    37,    38,    39,    40,    13,
   -15,   -13 ]

racc_action_check = [
    18,    18,    18,    18,    18,    33,     4,    16,    33,     0,
     0,     0,    22,     8,    22,    25,    25,    25,     7,     3,
     7,    17,    17,    17,    15,    15,    15,    14,    14,    14,
    21,    13,     6,    26,    27,    28,    29,    30,    31,     1,
    34,    35 ]

racc_action_pointer = [
    -3,    39,   nil,    17,     0,   nil,    26,    15,     7,   nil,
   nil,   nil,   nil,    31,    15,    12,     1,     9,    -7,   nil,
   nil,    27,     8,   nil,   nil,     3,    27,    28,    29,    30,
    31,    32,   nil,     2,    34,    35,   nil,   nil,   nil,   nil,
   nil ]

racc_action_default = [
   -25,   -25,    -1,    -4,    -5,    -6,    -7,   -14,   -25,   -15,
   -22,   -23,   -24,   -25,    -3,   -25,   -25,   -25,   -25,    41,
    -2,   -14,   -25,   -13,   -16,   -25,   -12,   -25,   -25,   -25,
   -25,   -25,    -8,   -10,    -9,   -11,   -17,   -18,   -19,   -20,
   -21 ]

racc_goto_table = [
     6,     2,    23,    21,    23,    21,    22,     1,    26,    34,
   nil,   nil,    35,    33,     6,    20 ]

racc_goto_check = [
     6,     2,     4,     7,     4,     7,     8,     1,     8,     9,
   nil,   nil,     4,     7,     6,     2 ]

racc_goto_pointer = [
   nil,     7,     1,   nil,   -13,   nil,     0,   -12,    -9,   -16,
   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,    24,     7,     8,     9,
    17 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 16, :_reduce_1,
  3, 17, :_reduce_2,
  2, 17, :_reduce_3,
  1, 17, :_reduce_4,
  1, 18, :_reduce_none,
  1, 18, :_reduce_none,
  1, 18, :_reduce_none,
  4, 21, :_reduce_8,
  4, 20, :_reduce_9,
  4, 20, :_reduce_10,
  4, 20, :_reduce_11,
  3, 19, :_reduce_12,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  3, 25, :_reduce_17,
  3, 25, :_reduce_18,
  3, 25, :_reduce_19,
  3, 25, :_reduce_20,
  3, 25, :_reduce_21,
  1, 24, :_reduce_22,
  1, 24, :_reduce_23,
  1, 22, :_reduce_24 ]

racc_reduce_n = 25

racc_shift_n = 41

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :OPEN_PAREN => 3,
  :CLOSE_PAREN => 4,
  ":" => 5,
  " " => 6,
  "+" => 7,
  "-" => 8,
  "*" => 9,
  "/" => 10,
  "**" => 11,
  :FLOAT => 12,
  :INTEGER => 13,
  :IDENTIFIER => 14 }

racc_nt_base = 15

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "\":\"",
  "\" \"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "\"**\"",
  "FLOAT",
  "INTEGER",
  "IDENTIFIER",
  "$start",
  "target",
  "program",
  "statement",
  "expression",
  "assignment",
  "method_call",
  "identifier",
  "expressable",
  "literal",
  "logical" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'generator.y', 2)
  def _reduce_1(val, _values, result)
     result = [:program, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 4)
  def _reduce_2(val, _values, result)
     result = [val[0], *val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 5)
  def _reduce_3(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 6)
  def _reduce_4(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

module_eval(<<'.,.,', 'generator.y', 10)
  def _reduce_8(val, _values, result)
     result = [:call, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 12)
  def _reduce_9(val, _values, result)
     result = [:assignment, val[0], val[3]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 13)
  def _reduce_10(val, _values, result)
     result = [:assignment, val[0], val[3]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 14)
  def _reduce_11(val, _values, result)
     result = [:assignment, val[0], val[3]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 16)
  def _reduce_12(val, _values, result)
     result = [val[1], val[0], val[2]] 
    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'generator.y', 20)
  def _reduce_17(val, _values, result)
     result = :addition 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 21)
  def _reduce_18(val, _values, result)
     result = :subtraction 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 22)
  def _reduce_19(val, _values, result)
     result = :multiplication 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 23)
  def _reduce_20(val, _values, result)
     result = :division 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 24)
  def _reduce_21(val, _values, result)
     result = :exponentiation 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 26)
  def _reduce_22(val, _values, result)
     result = [:float, val[0].to_f] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 27)
  def _reduce_23(val, _values, result)
     result = [:integer, val[0].to_i] 
    result
  end
.,.,

module_eval(<<'.,.,', 'generator.y', 29)
  def _reduce_24(val, _values, result)
     result = [:identifier, val[0]]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Generator
  end   # module Ast
